
spring:
  datasource:  # pode ser removido se loja.yml estiver configurado corretamente
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/loja

jpa:
  show-sql: true
  properties:
    hibernate:
      ddl-auto: update
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  # database: postgresql  # desnecessário se o database-platform já foi definido
