

spring:
  datasource:           #CONTEUDO MOVIDO PARA O ARQUIVO fornecedor.yml
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/loja
  jpa:
   show-sql: true
   properties:
    hibernate:
      ddl-auto: update
      format_sql: true
    database: postgresql
    properties:
      jdbc:
          lob:
            '[non_contextual_creation]': true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
 